### ISSUE TITLE
功能有些简单，希望加上右键菜单方便关闭标签

### ISSUE THREAD

**Issue by libsgh** [TerryZ/bTabs#1]
RT.

**Comment by TerryZ** [comment]
这。。。。。不是已经有X来关闭标签页了吗，这样不是比菜单方便多了

**Comment by lizhuangs** [comment]
同问。当标签比较多的时候，右键关闭当前，关闭所有，关闭左/右侧，关闭其它。

**Comment by TerryZ** [comment]
原来说的是这些功能，这些功能已在开发计划中，后续会增加，请关注

**Comment by libsgh** [comment]
看来是G了

**Comment by ajiho** [comment]
@libsgh  see [Quicktab](https://github.com/ajiho/quicktab)
